# -*- coding: utf-8 -*-
"""Modelo_Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bjjCjqQVcV952cW7pAC_SoRzr1hCqoPS
"""

#Se importan las librerias necesarias
from os import read
import sqlite3
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Se realiza la conexión con la base de datos
conexion = sqlite3.connect('datos.db')

#Se consulan los datos necesarios del SQL y se realiza la creación del dataframe
query = """
SELECT
    edad,
    hipertension,
    enfermedad_corazon,
    bmi,
    HbA1c_nivel,
    nivel_glucosa_sangre,
    diabetes
FROM NUEVA_TABLA
"""

dataset = pd.read_sql_query(query, conexion)

#Preparación de los datos para el modelo
X = dataset.drop(['diabetes'], axis=1)
Y = dataset['diabetes']

X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size=0.2, random_state=10)

#Se aplica el modelo de random forest
modelo_rf = RandomForestClassifier(n_estimators=120, max_depth=50, min_samples_split=2, min_samples_leaf=1, random_state=1)
modelo_rf.fit(X_Train, Y_Train)

#Se realizan las predicciones y se evalua el modelo
predicciones_rf = modelo_rf.predict(X_Test)

# Accuracy
accuracy = accuracy_score(Y_Test, predicciones_rf)